### ISSUE TITLE
barplot纵轴标签问题

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#12]
![barplot](https://user-images.githubusercontent.com/12031874/28810063-2fe63496-76ba-11e7-88be-e0c9d14dd486.png)

**Comment by Cloud2016** [comment]
![barplot_improve](https://user-images.githubusercontent.com/12031874/28810279-7aa94ecc-76bb-11e7-84f6-3f26bd5eaeaf.png)

**Comment by Cloud2016** [comment]
![barplot3](https://user-images.githubusercontent.com/12031874/28812405-2a9aca1c-76c7-11e7-9bbf-493a7e73e196.png)

**Comment by Cloud2016** [comment]
![barplot4](https://user-images.githubusercontent.com/12031874/28815599-7b307cc6-76d4-11e7-88a4-f3c5284cda08.png)

**Comment by Cloud2016** [comment]
```r
data(NCI60,package ="ISLR") # 加载数据		
myData <- sort(table(NCI60$labs))		
par(mar=c(5,2.5,1,1))	
barCenters <- barplot(myData,col = "lightblue",axes = FALSE,
			axisnames=FALSE,border ="white")				
text(x = barCenters, y = par("usr")[3]-.2, srt = 45,
     adj = 1, labels = names(myData), xpd = TRUE)
axis(2, labels = seq(0,9,by=1), at = seq(0,9,by=1), 
	 las = 1 , col = "gray") 
```

**Comment by Cloud2016** [comment]
![barplot5](https://user-images.githubusercontent.com/12031874/28816143-4c16e1e4-76d6-11e7-8176-cc3cf0ced603.png)

**Comment by Cloud2016** [comment]
```r
data(NCI60,package ="ISLR") # 加载数据		
myData <- sort(table(NCI60$labs), decreasing = TRUE)		
par(mar=c(2,7,.5,1))	
barCenters <- barplot(myData,col = "lightblue",axes = FALSE,
			axisnames=FALSE,horiz=TRUE,border ="white")				
text(y = barCenters, x = par("usr")[3],
     adj = 1, labels = names(myData), xpd = TRUE)
axis(1, labels = seq(0,9,by=1), at = seq(0,9,by=1),  las = 1 , col = "gray") 
```

**Comment by Cloud2016** [comment]
COS统计之都论坛 帖子参见
<https://d.cosx.org/d/417769-barplot-y>
