### ISSUE TITLE
想一劳永逸地把所有R包引用信息都保存

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#13]
想一劳永逸地把所有R包引用信息都保存
```r
citefun <- function(x){
  knitcitations::write.bibtex(citation(x),file = "ref.bib",append = TRUE)
}
r_info <- sessionInfo()
lapply(names(r_info$otherPkgs),citefun)

is.na()  
packages <- readRDS("packages.RDS") 
pkgs <- packages$Package[!unlist(lapply(packages$Author,is.na))]

unlist(lapply(packages$Author,is.na))


# 通过 citations 提取 author given family字段
## A citation with more than one bibentry:
cm <- tryCatch(citation("ABCoptim"),
               error = function(e) {
                 warning("Recommended package 'mgcv' is not installed properly")
                 stop(e$message) })
cm # short entries (2-3 lines each)
```

**Comment by Cloud2016** [comment]
如何一口气把所有已安装的R包的引用搞定
```r
cite_pkgs <- function(x){
  knitcitations::write.bibtex(citation(x),file = "ref.bib",append = TRUE)
}
pkgs <- list.files(.libPaths())
lapply(pkgs,cite_pkgs)
```
对绝大多数的R包，使用```citation```函数是不会出错的，但是有些R包信息不全，导致上面程序运行终止，我希望跳过这些信息不全的R包，但是要把这些R包的名字记录下来。

Results written to file 'ref.bib'
Writing 1 Bibtex entries ... OK
Results written to file 'ref.bib'
Error in parse(con) : 8:31: unexpected INCOMPLETE_STRING
7:           person("George", "Vega Yon"),
8:           person("Enyelbert", "Mu
                                 ^
In addition: Warning message:
In parse(con) :
  invalid input found on input connection 'E:/Program/library/ABCoptim/CITATION'
