### ISSUE TITLE
类别太多，横着放，点图

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#14]
![default](https://user-images.githubusercontent.com/12031874/28908020-c4770c08-7853-11e7-90c7-55cf496480dd.png)

**Comment by Cloud2016** [comment]
类别标签是数字，还是可以正着放，如<https://cosx.org/2017/05/random-number-generation/>，下面只考虑一个图不做对比
![hist_plot](https://user-images.githubusercontent.com/12031874/28908283-6493aff6-7855-11e7-97df-34f13da0d34d.png)
