### ISSUE TITLE
要不要用图例，用图例就是添加信息

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#15]
![cumcm2011a_02](https://user-images.githubusercontent.com/12031874/28908702-9ac4e53e-7857-11e7-8ea1-ef225c20bec8.png)

**Comment by Cloud2016** [comment]
![airquality_03](https://user-images.githubusercontent.com/12031874/28908725-b5ae8350-7857-11e7-9862-998be4fdf160.png)

**Comment by Cloud2016** [comment]
要不要上色，怎么上色
![clarity_gray_rainbow](https://user-images.githubusercontent.com/12031874/28909173-e43dd5f2-7859-11e7-8b16-c0701878a657.png)

**Comment by Cloud2016** [comment]
正例，为了对比，要上色，图例相应地加上
![bed_net](https://user-images.githubusercontent.com/12031874/28909799-8cc84412-785c-11e7-8307-4b4c5131f4a2.png)
