### ISSUE TITLE
3D barplot

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#16]
来自MATLAB的样例
![img1](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/35274/versions/3/previews/html/Bar_Plot_3D_01.png)
还有这
![img2](https://cn.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/52067/versions/1/screenshot.jpg)

哼，怎能没有R版<http://www.cpwardell.com/2015/08/28/legoplots-in-r-3d-barplots-in-r/>
![img3](http://www.cpwardell.com/wp-content/uploads/2015/08/cpw_context_transparent.png)

这个3D图，也是魔性，上了nature <http://www.nature.com/ng/journal/v45/n5/full/ng.2591.html?foxtrotcallback=true>
![img4](https://images.nature.com/full/nature-assets/ng/journal/v45/n5/images/ng.2591-F1.jpg)

**Comment by Cloud2016** [comment]
![airline_passenger](https://user-images.githubusercontent.com/12031874/28926489-867954a0-789a-11e7-8b37-ffcc845c3fae.png)
一次尝试
```r
myData <- matrix(AirPassengers,ncol =12,byrow = TRUE,
		 dimnames = list(1948+seq(12),
		   c( "Jan", "Feb", "Mar", "Apr",
			"May", "Jun", "Jul", "Aug", 
			"Sep", "Oct", "Nov", "Dec")))
x <- 1948 + seq(12)
y <- seq(from = 12 ,to =1,length.out =12)
# y <- c("Jan", "Feb", "Mar", "Apr",
	  # "May", "Jun", "Jul", "Aug", 
	  # "Sep", "Oct", "Nov", "Dec")
z <- myData
library(colormap)
library(plot3D)
colorBar <- colormap_pal(colormap=colormaps$viridis, reverse = TRUE,alpha = 1)(10)
hist3D(x, y, z, xlab = "Year", ylab = "Month", zlab = "# of Airline Passengers",
		main = "Monthly Airline Passenger Numbers 1949-1960",
		col = colorBar, colkey = FALSE, bty = "b2",theta=30, phi=20,r=50,d=0.1,
		expand = 0.5,ltheta=90, lphi=180, lighting = TRUE,
		ticktype = "detailed",border = "lightblue")

```

**Comment by Cloud2016** [comment]
![demo](https://user-images.githubusercontent.com/12031874/28926943-dc559d9c-789b-11e7-8038-005c92df5364.png)

**Comment by Cloud2016** [comment]
```r
myData <- matrix(AirPassengers,ncol =12,byrow = TRUE,
				 dimnames = list(1948+seq(12),
							c("Jan", "Feb", "Mar", "Apr",
							  "May", "Jun", "Jul", "Aug", 
						      "Sep", "Oct", "Nov", "Dec")))
x <- 1948 + seq(12)
y <- seq(from = 12 ,to =1,length.out =12)
# y <- c("Jan", "Feb", "Mar", "Apr",
	  # "May", "Jun", "Jul", "Aug", 
	  # "Sep", "Oct", "Nov", "Dec")
z <- myData
library(colormap)
library(plot3D)
colorBar <- colormap_pal(colormap=colormaps$viridis, reverse = TRUE,alpha = 1)(10)

pdf(file="AirlinePassenger.pdf")

hist3D(x, y, z, xlab = "Year", ylab = "Month", zlab = "# of Airline Passengers",
		main = "Monthly Airline Passenger Numbers 1949-1960",
		col = colorBar, colkey = FALSE,theta=30, phi=20,r=50,d=0.1,
		expand = 0.5,ltheta=-55, lphi=180, lighting = TRUE,
		ticktype = "detailed",space = .3, bty = "b2",facets = FALSE )
		
# box = FALSE  将去掉 坐标轴标签 刻度标签 标题		
# bty “b”, “b2”, “f”, “g”, “bl”, “bl2”, “u”, “n”
# space = .3 柱子之间的间隔
# facets = TRUE 柱子周围是否上色
# ltheta : 灯光的位置
hist3D(x, y, z, xlab = "Year", ylab = "Month", zlab = "# of Airline Passengers",
		main = "Monthly Airline Passenger Numbers 1949-1960",
		col = "lightblue", colkey = FALSE, bty = "b2",theta=30, phi=20,r=50,d=0.1,
		expand = 0.5,ltheta=-45, lphi=180, lighting = F,
		ticktype = "detailed",space = .3,border = "whitesmoke")		

hist3D(x, y, z, xlab = "Year", ylab = "Month", zlab = "# of Airline Passengers",
		main = "Monthly Airline Passenger Numbers 1949-1960",
		col = colorBar, colkey = FALSE,theta=30, phi=20,r=50,d=0.1,
		expand = 0.5, ltheta=-120, lphi=180, lighting = TRUE,
		ticktype = "detailed",space = .3, bty = "b2",facets = TRUE)
		
dev.off()
```

**Comment by Cloud2016** [comment]
![airlinepassenger_ _1](https://user-images.githubusercontent.com/12031874/28929250-1b503664-78a2-11e7-9119-6dde6255ae63.png)
![airlinepassenger_ _2](https://user-images.githubusercontent.com/12031874/28929261-212cff04-78a2-11e7-88c9-f2c1389ca15a.png)
![airlinepassenger_ _3](https://user-images.githubusercontent.com/12031874/28929269-252ff66a-78a2-11e7-8a80-2c43cec5959d.png)

**Comment by Cloud2016** [comment]
![yuantu](https://github.com/Cloud2016/R-Packages-Developers/blob/master/figure/AirlinePassenger.svg)

**Comment by Cloud2016** [comment]
![img](https://cn.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/63449/versions/1/previews/html/Bivariate_Histogram_Plot_01.png)

二维直方图

**Comment by Cloud2016** [comment]
![airlinepassenger](https://user-images.githubusercontent.com/12031874/29644438-993e3efc-88a8-11e7-94ba-c04e57f15e4c.png)
