### ISSUE TITLE
3D map barplot

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/R-Packages-Developers#19]
[excel 2016 power map](https://www.youtube.com/watch?v=CoeL3_5M2zA) U.S. Power Production: A Power Map for Excel Tour  微软官方出品

[Power Map](https://www.youtube.com/watch?v=vNQ7ir-9TqY)
Excel 2013 - Exemple de présentation de données statistiques sur Power Map 图类型同上

**Comment by Cloud2016** [comment]
[power map heat plot](https://www.youtube.com/watch?v=xAQQClV3k1E)  3D 密度热图
